const twelveYear = {
  id: '2012',
  name: 'Night Visions',
  imgsrc: './images/2012.jpg',
  list: [
    'Radioactive',
    'Tiptoe',
    `It's Time`,
    'Demons',
    'On Top of the World',
    'Amsterdam',
    'Hear Me',
    'Every Night',
    'Bleeding Out',
    'Underdog',
    'Nothing Left to Say/Rocks',
  ],
  youtube: [
    'https://youtu.be/ktvTqknDobU',
    'https://youtu.be/ajjj4pLnjz8',
    'https://youtu.be/sENM2wA_FTg',
    'https://youtu.be/mWRsgZuwf_8',
    'https://youtu.be/w5tWYmIOWGk',
    'https://youtu.be/TKtPXO5iEnA',
    'https://youtu.be/1Yr683VLxes',
    'https://youtu.be/kuijhOvKyYg',
    'https://youtu.be/kcMU_iT9aDM',
    'https://youtu.be/JCUV43T7HZ0',
    'https://youtu.be/Bn7eYibzmTs',
  ],
};

const fifteenYear = {
  id: '2015',
  name: `Smoke + Mirrors`,
  imgsrc: './images/2015.jpg',
  list: [
    'Shots',
    'Gold',
    'Smoke + Mirrors',
    `I'm So Sorry`,
    'I Bet My Life',
    'Polaroid',
    'Friction',
    'It Comes Back to You',
    'Dreams',
    'Trouble',
    'Summer',
    'Hopeless Opus',
    'The Fall',
  ],
  youtube: [
    'https://youtu.be/qQrgto184Tk',
    'https://youtu.be/Rl3ELiPXFRo',
    'https://youtu.be/VDPnaTQF6Dw',
    'https://youtu.be/0HgJwrwEEKQ',
    'https://youtu.be/4ht80uzIhNs',
    'https://youtu.be/wmjyO-r1OhA',
    'https://youtu.be/o0aoh363PI4',
    'https://youtu.be/3x6Y2fYGrmM',
    'https://youtu.be/BWu7JDETw_I',
    'https://youtu.be/k4l5SLs5u8A',
    'https://youtu.be/TT8Pp2eY3Cs',
    'https://youtu.be/BoVKJq5Qvxs',
    'https://youtu.be/8MWglxkw1y4',
  ],
};
const seventeenYear = {
  id: '2017',
  name: `Evolve`,
  imgsrc: './images/2017.jpg',
  list: [
    'Next To Me',
    `I Don't Know Why`,
    'Whatever It Takes',
    `Believer`,
    'Walking the Wire',
    'Rise Up',
    `I'll Make It Up to You`,
    'Yesterday',
    'Mouth of the River',
    'Thunder',
    'Start Over',
    'Dancing In the Dark',
  ],
  youtube: [
    'https://youtu.be/Txlk7PiHaGk',
    'https://youtu.be/RxB9j6gtRX0',
    'https://youtu.be/gOsM-DYAEhY',
    'https://youtu.be/7wtfhZwyrcc',
    'https://youtu.be/1nv9br7P7g0',
    'https://youtu.be/x12CWu3V0lg',
    'https://youtu.be/q6KvD4kZv94',
    'https://youtu.be/3x6Y2fYGrmM',
    'https://youtu.be/dJfYS0rVrbk',
    'https://youtu.be/41Qt2ZRkH0g',
    'https://youtu.be/fKopy74weus',
    'https://youtu.be/0uxEMkzi8B8',
    'https://youtu.be/fMjFEKJbCw8',
  ],
};
const eighteenYear = {
  id: '2018',
  name: `Origins`,
  imgsrc: './images/2018.jpg',
  list: [
    'Natural',
    'Boomerang',
    'Machine',
    `Cool Out`,
    'Bad Liar',
    'West Coast',
    'Zero',
    'Bullet in a Gun',
    'Digital',
    'Only',
    'Stuck',
    'Love',
  ],
  youtube: [
    'https://youtu.be/0I647GU3Jsc',
    'https://youtu.be/BDjfMI6QvxQ',
    'https://youtu.be/BahtnT13vH8',
    'https://youtu.be/grfk5Yqygw8',
    'https://youtu.be/I-QfPUz1es8',
    'https://youtu.be/5Yj4j_lZMBo',
    'https://youtu.be/j60ClcNYWu4',
    'https://youtu.be/LHWYaV6WLQo',
    'https://youtu.be/AWf-rjq5dzs',
    'https://youtu.be/_CNTxeffmLs',
    'https://youtu.be/RfC5WtzRKiY',
    'https://youtu.be/cQbAm4dIDKA',
  ],
};
